# Numpy
numpy는 수학, 과학 연산을 위한 Python 패키지로, python이 대규모 수학 연산에 속도가 느리다는 단점을 C나 포트란으로 작성하여 해결하였다. 기본적으로 array형식으로 자료를 생성하고 이를 바탕으로 인덱스, 처리, 연산을 한다.

### Numpy 모듈 불러오기

- `import`는 모듈을 불러오는 기능을 한다. 옆에 `numpy`가 있으므로 numpy 모듈을 불러온다.
- `as`는 모듈에 aliasing을 하는 것으로 numpy라는 말 대신 np라는 형태로 사용하겠다는 뜻이다.

In [1]:
import numpy as np

## 배열 생성하기
배열을 생성하는 방법은 다양하다. 대표적으로

- 직접 값을 넣어서 생성 (np.array)
- 어떤 동일한 값을 채워서 생성 (np.zeros, np.ones, np.full, ...)
- 어떤 규칙에 맞게 값을 채워서 생성 (np.arnage, np.linspace, ...)
- 랜덤한 값으로 배열 생성 (np.random.rand, np.random.randint, ...)

### 값을 넣어서 배열 생성
#### np.array
스칼라 값이나 리스트, 튜플을 사용해서 생성할 수 있다.

In [2]:
array1 = np.array(0)
array2 = np.array([1,2,3,4])
array3 = np.array((5,6,7,8))

print(array1)
print(array2)
print(array3)

0
[1 2 3 4]
[5 6 7 8]


In [3]:
array = np.array([45,23,21])
array

array([45, 23, 21])

### 어떤 동일한 값을 채워서 생성

#### shape
배열의 형태를 말한다. shape가 [2, 3]이라는 값이 있다면 이 행렬은 2행 3열이라는 뜻이다. shape를 통해 배열이 어떤 형태를 가지고 있는지 알 수 있다.

In [4]:
array = np.array([[1, 2, 3],
                  [4, 5, 6]])
print(array.shape)

(2, 3)


In [5]:
array = np.array([[1,2],
                [2,3],
                [3,4]])
print(array.shape)

(3, 2)


#### np.zeros
배열의 값에 0을 채워서 만든다. 만약 [2, 3]이라는 값을 넣어주게 되면 [2, 3]값을 가진 배열이 아닌 2행 3열 형태의 배열이 생성된다

In [6]:
np.zeros(1)

array([0.])

In [7]:
np.zeros([4])

array([0., 0., 0., 0.])

In [8]:
np.zeros([2, 2])

array([[0., 0.],
       [0., 0.]])

In [9]:
np.zeros([2, 2, 3])

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
np.zeros(10, dtype=np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

#### np.ones
np.zeros와 마찬가지로 shape를 입력 받지만 0 대신 1로 채워서 출력한다

In [11]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### np.full
np.zeros와 마찬가지로 shape를 입력 받지만 어떤 수를 채울 지를 결정할 수 있다

In [12]:
np.full([5,3],5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

### 연습 : np.zeros, np.ones, np.full 을 활용해 다양한 배열을 생성하자

### 어떤 규칙에 맞게 배열 생성

#### np.arange

- np.arange(x) : 0부터 x 미만의 값까지 생성한다.
- np.arange(x, y) : x부터 y 이전값까지 생성한다.
- np.arnage(x, y, z) : x부터 y 이전값까지 z만큼 이동한 값들의 배열을 생성한다.

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [15]:
np.arange(1,10, 2)

array([1, 3, 5, 7, 9])

In [16]:
np.arange(10, 1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [17]:
np.arange(1, 10, 5)

array([1, 6])

#### np.linspace(x)
- np.linspace(x, y, z) : x, y 포함 사이 값 z개를 생성한다.

In [18]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

### 연습 : np.arange, np.linspace를 활용해 다양한 배열을 생성하자

In [20]:
np.linspace(1,15,32)

array([ 1.        ,  1.4516129 ,  1.90322581,  2.35483871,  2.80645161,
        3.25806452,  3.70967742,  4.16129032,  4.61290323,  5.06451613,
        5.51612903,  5.96774194,  6.41935484,  6.87096774,  7.32258065,
        7.77419355,  8.22580645,  8.67741935,  9.12903226,  9.58064516,
       10.03225806, 10.48387097, 10.93548387, 11.38709677, 11.83870968,
       12.29032258, 12.74193548, 13.19354839, 13.64516129, 14.09677419,
       14.5483871 , 15.        ])

### 랜덤한 값으로 배열 생성

#### np.random.rand
list나 tuple이 아니라 parameter에 각각 원하는 크기를 넣어서 shape를 결정하고 배열 생성

In [21]:
np.random.rand(2,2)

array([[0.49105557, 0.6452086 ],
       [0.4243109 , 0.88192592]])

#### np.random.random
list나 tuple을 넣어서 배열 생성

In [22]:
np.random.random([2, 2])

array([[0.25941419, 0.12031127],
       [0.59215426, 0.21042198]])

In [23]:
np.random.random([10,4])

array([[0.15618265, 0.42095333, 0.74009951, 0.37613228],
       [0.31966377, 0.61324671, 0.31503113, 0.18446731],
       [0.63886927, 0.45803076, 0.4454598 , 0.84040773],
       [0.0761221 , 0.8991539 , 0.62715362, 0.04557777],
       [0.24255338, 0.02845335, 0.02691573, 0.05311267],
       [0.844262  , 0.0669911 , 0.89754901, 0.85997341],
       [0.73189782, 0.59836922, 0.77799315, 0.49217761],
       [0.64114733, 0.11051337, 0.17429761, 0.10683405],
       [0.22830413, 0.46859889, 0.20766497, 0.74212885],
       [0.85380111, 0.24740686, 0.71715346, 0.89130773]])

#### np.random.randint

- np.random.randint(x) : x미만 값 사이의 임의의 integer 값 생성
- np.random.randint(x, y) : x부터 y미만 값 사이의 임의의 integer 값 생성

In [24]:
np.random.randint(10)

6

In [25]:
np.random.randint(2,6)

3

### numpy 연산

배열을 생성 뿐만 아니라 연산에 관한 다양한 함수를 제공한다. 두 개의 배열을 사칙연산 해보자.

In [26]:
a = np.array([[1, 1],
              [1, 1]])
b = np.array([[2, 2],
              [2, 2]])
print('a =')
print(a)
print('b =')
print(b)

a =
[[1 1]
 [1 1]]
b =
[[2 2]
 [2 2]]


#### np.add or +

In [27]:
np.add(a, b)

array([[3, 3],
       [3, 3]])

In [28]:
a + b

array([[3, 3],
       [3, 3]])

#### np.subtract or -

In [29]:
np.subtract(a, b)

array([[-1, -1],
       [-1, -1]])

In [30]:
a - b

array([[-1, -1],
       [-1, -1]])

#### np.multiply or *

In [31]:
np.multiply(a, b)

array([[2, 2],
       [2, 2]])

In [32]:
a * b

array([[2, 2],
       [2, 2]])

#### np.divide or /

In [33]:
np.divide(a, b)

array([[0.5, 0.5],
       [0.5, 0.5]])

In [34]:
a / b

array([[0.5, 0.5],
       [0.5, 0.5]])

이외에도 행렬 곱, 각 배열 원소의 합, 곱 또한 지원한다.

## 그 외 다양한 함수들
단순한 사칙연산 뿐만 아니라, 행렬곱, 배열들의 합, 평균, 최대/최소값 등을 구할 수 있다. 

In [35]:
a = np.array([1, 2])
b = np.array([[3, 4], [5, 6]])
print('a =')
print(a)
print('b =')
print(b)

a =
[1 2]
b =
[[3 4]
 [5 6]]


#### np.dot : 행렬곱

In [36]:
np.dot(a, b) # [1, 2] x [[3, 4],
             #           [5, 6]] 
             #
             # = [1 x 3 + 2 x 5, 1 x 4 + 2 x 6]
             # = [13, 16]

array([13, 16])

In [37]:
array1 = np.array([[3,2,1],[5,6,7]])
array2 = np.array([[4,3],[6,5],[9,1]])
np.dot(array1,array2)


array([[ 33,  20],
       [119,  52]])

#### np.sum : 합

In [38]:
np.sum(a)

3

In [39]:
np.sum(b)

18

In [40]:
sum_axis_0 = np.sum(b, axis=0)
sum_axis_1 = np.sum(b, axis=1)

print("b = ")
print(b)

print("Axis 0에 대한 합 = ")
print(sum_axis_0)

print("Axis 1에 대한 합 = ")
print(sum_axis_1)

b = 
[[3 4]
 [5 6]]
Axis 0에 대한 합 = 
[ 8 10]
Axis 1에 대한 합 = 
[ 7 11]


In [41]:
array4=np.array([[1,3,1],[5,3,4],[6,1,2]])
print(array4)
print(np.sum(array4))
print(np.sum(array4,axis=0))
print(np.sum(array4,axis=1))

[[1 3 1]
 [5 3 4]
 [6 1 2]]
26
[12  7  7]
[ 5 12  9]


#### np.mean : 평균

In [42]:
np.mean(a)

1.5

In [43]:
np.mean(b)

4.5

In [44]:
np.mean(b, axis=0)

array([4., 5.])

In [45]:
np.mean(b, axis=1)

array([3.5, 5.5])

#### np.max : 최댓값

In [46]:
np.max(a)

2

In [47]:
np.max(b)

6

In [48]:
np.max(b, axis=0)

array([5, 6])

In [49]:
np.max(b, axis=1)

array([4, 6])

#### np.min : 최솟값

In [50]:
np.min(a)

1

In [51]:
np.min(b)

3

In [52]:
np.min(b, axis=0)

array([3, 4])

In [53]:
np.min(b, axis=1)

array([3, 5])

### np.reshape : shape를 변경

shape를 다른 형태로 변경할 수 있다.

예]

- [2, 2, 3] = [4, 3]
- [3, 2] = [2, 3]

In [54]:
import numpy as np
a = np.zeros([2, 2, 3]) 
b = np.ones([3, 2])

print("a = ")
print(a)

print("a.shape = ", a.shape)
print()

print("b = ")
print(b)
print("b.shape = ", b.shape)

a = 
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
a.shape =  (2, 2, 3)

b = 
[[1. 1.]
 [1. 1.]
 [1. 1.]]
b.shape =  (3, 2)


In [55]:
a1 = a.reshape([4,3]) # np.reshape(a, [4, 3]) 과 동일

print("a1 = ")
print(a1)
print("a1.shape = ", a1.shape)

a1 = 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
a1.shape =  (4, 3)


In [56]:
b1 = b.reshape([2,3])

print("b1 = ")
print(b1)
print("b1.shape = ", b1.shape)

b1 = 
[[1. 1. 1.]
 [1. 1. 1.]]
b1.shape =  (2, 3)


In [58]:
a=np.arange(1,13)
print(a)
a1=a.reshape([2,6])
print(a1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


## GOod