## 문제 1
`tf.constant()`으로 '자신의 이름'을 저장하여 Session을 통해 출력하도록 실행한다.

In [1]:
import tensorflow as tf

my_name = tf.constant('TaehoLi')
sess = tf.Session()
sess.run(my_name)

b'TaehoLi'

## 문제 2
임의의 8개 정수로 shape가 [8]인 구성된 tensor를 만들고, Tensor 값을 출력한다.

In [2]:
a = tf.constant([1,2,3,4,5,6,7,8])
sess = tf.Session()
sess.run(a)

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

## 문제 3
문제 2번의 tensor를 tf.reshape()함수로 변환하여 2행 4열로 만들어고 Session을 통해 출력한다.

In [3]:
b = tf.reshape(a, [2,4])
sess = tf.Session()
sess.run(b)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)

## 문제 4
문제 3번의 tensor를 tf.transpose()함수를 사용하여 전치행렬을 만들고 하고 Session을 통해 출력한다.

In [4]:
c = tf.transpose(b)
sess = tf.Session()
sess.run(c)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]], dtype=int32)

## 문제 5
3번, 4번의 tensor 행렬곱을 실행하고 그 결과를 Session을 통해 출력한다.

In [5]:
d = tf.matmul(b, c)
sess = tf.Session()
sess.run(d)

array([[ 30,  70],
       [ 70, 174]], dtype=int32)

## 문제 6
중첩 for 문을 사용하여 2차원 배열을 만든다. 이 때 shape \[4,8\]이 되도록 하고 임의의 값을 넣는다. 이 값을 tensor에 넣은 다음 rank가 3이 되도록 shape를 변경한다.

In [6]:
N, M = 4, 8
arr = [[1 for j in range(M)] for i in range(N)]

e = tf.constant([arr])
f = tf.reshape(e, [2,2,8])
sess = tf.Session()

print(e.shape)
print(f.shape)
print(sess.run(f))

(1, 4, 8)
(2, 2, 8)
[[[1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]]]


## 문제 7
1부터 10까지 수를 가진 배열을 만들고 선언하여 tf.placeholder() 넣어서 Session을 통해 출력한다.

In [7]:
import numpy as np

g = tf.placeholder(tf.int32)
sess = tf.Session()
sess.run(g, feed_dict={g: np.arange(1,11)})

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

## 문제 8
문제 7번처럼 tf.placeholder()에 값을 넣되, 배열들의 총합을 구하여 Session을 통해 출력한다. reduce_sum 함수를 사용한다.

In [8]:
h = tf.placeholder(tf.int32)
sess = tf.Session()
sess.run(h, feed_dict={h: np.sum(np.arange(1,11))})

array(55, dtype=int32)

## 문제 9

tf.placeholder()를 2개와 이 2개의 텐서로 사칙연산(덧셈, 뺄셈, 곱셈, 나눗셈)하는 tensor를 만든 다음, Session을 통해 출력한다. 이 때 placeholder의 텐서 shape가 [5]인 임의의 배열이 들어가도록 한다.

In [9]:
i = tf.placeholder(tf.float32)
j = tf.placeholder(tf.float32)
k = i+j
l = i-j
m = i*j
n = i/j
sess = tf.Session()
sess.run(n, feed_dict={i: np.random.random([1,5]), j: np.random.random([1,5])})

array([[4.3011923 , 1.5305688 , 0.35991576, 8.805467  , 1.2203012 ]],
      dtype=float32)